---
abstract: 'Client library for Ukigumo'
author:
  - 'Tokuhiro Matsuno <tokuhirom+cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ukigumo-Client
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0
  Encode::Locale: 0
  File::HomeDir: 0
  JSON: 2
  LWP::UserAgent: 6
  Mouse: 0
  String::IRC: 0
  Test::Requires: 0
  Time::Piece: 1.15
  URI::Escape: 0
  Ukigumo::Common: 0.03
  YAML::Tiny: 0
  perl: 5.010000
version: 0.14
