---
abstract: 'Client library for Ukigumo'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  File::Temp: '0'
  File::pushd: '0'
  Test::More: '0.98'
  Test::Requires: '0'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ukigumo-Client
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Ukigumo::Client:
    file: lib/Ukigumo/Client.pm
    version: '0.23'
  Ukigumo::Client::Executor::Auto:
    file: lib/Ukigumo/Client/Executor/Auto.pm
  Ukigumo::Client::Executor::Callback:
    file: lib/Ukigumo/Client/Executor/Callback.pm
  Ukigumo::Client::Executor::Command:
    file: lib/Ukigumo/Client/Executor/Command.pm
  Ukigumo::Client::Executor::Perl:
    file: lib/Ukigumo/Client/Executor/Perl.pm
  Ukigumo::Client::Executor::Prove:
    file: lib/Ukigumo/Client/Executor/Prove.pm
  Ukigumo::Client::Notify::Callback:
    file: lib/Ukigumo/Client/Notify/Callback.pm
  Ukigumo::Client::Notify::Debug:
    file: lib/Ukigumo/Client/Notify/Debug.pm
  Ukigumo::Client::Notify::GitHubStatuses:
    file: lib/Ukigumo/Client/Notify/GitHubStatuses.pm
  Ukigumo::Client::Notify::Growl:
    file: lib/Ukigumo/Client/Notify/Growl.pm
  Ukigumo::Client::Notify::Ikachan:
    file: lib/Ukigumo/Client/Notify/Ikachan.pm
  Ukigumo::Client::Role::VC:
    file: lib/Ukigumo/Client/Role/VC.pm
  Ukigumo::Client::VC::Callback:
    file: lib/Ukigumo/Client/VC/Callback.pm
  Ukigumo::Client::VC::Git:
    file: lib/Ukigumo/Client/VC/Git.pm
  Ukigumo::Client::VC::SVN:
    file: lib/Ukigumo/Client/VC/SVN.pm
recommends:
  Growl::Any: '0'
requires:
  Capture::Tiny: '0'
  Encode::Locale: '0'
  File::HomeDir: '0'
  HTTP::Request::Common: '0'
  JSON: '2'
  LWP::UserAgent: '6'
  Mouse: '0'
  Scope::Guard: '0'
  String::IRC: '0'
  Time::Piece: '1.15'
  URI::Escape: '0'
  Ukigumo::Common: '0.04'
  YAML::Tiny: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/ukigumo/Ukigumo-Client/issues
  homepage: https://github.com/ukigumo/Ukigumo-Client
  repository: git://github.com/ukigumo/Ukigumo-Client.git
version: '0.23'
x_contributors:
  - 'mattn <mattn.jp@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'moznion <moznion@gmail.com>'
